/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.ABMvendedor;

/**
 *
 * @author gustavo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMVendedores = new javax.swing.JMenu();
        jMGestionarVendedores = new javax.swing.JMenuItem();
        jMComisionV = new javax.swing.JMenuItem();
        jMCobranzas = new javax.swing.JMenu();
        jMIngresos = new javax.swing.JMenuItem();
        jMListado = new javax.swing.JMenuItem();
        jMReporte = new javax.swing.JMenuItem();
        jMAreas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMVendedores.setText("Vendedores");
        jMVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMVendedoresActionPerformed(evt);
            }
        });

        jMGestionarVendedores.setText("Gestionar Vendedores");
        jMGestionarVendedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMGestionarVendedoresMouseClicked(evt);
            }
        });
        jMGestionarVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGestionarVendedoresActionPerformed(evt);
            }
        });
        jMVendedores.add(jMGestionarVendedores);

        jMComisionV.setText("Comisiones");
        jMVendedores.add(jMComisionV);

        jMenuBar.add(jMVendedores);

        jMCobranzas.setText("Cobranzas");

        jMIngresos.setText("Ingresos");
        jMCobranzas.add(jMIngresos);

        jMListado.setText("Listado");
        jMCobranzas.add(jMListado);

        jMReporte.setText("Reportes");
        jMCobranzas.add(jMReporte);

        jMenuBar.add(jMCobranzas);

        jMAreas.setText("Areas");
        jMAreas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMAreasMouseClicked(evt);
            }
        });
        jMAreas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAreasActionPerformed(evt);
            }
        });
        jMenuBar.add(jMAreas);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMGestionarVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGestionarVendedoresActionPerformed
        ABMvendedor gestionarVendedor = new ABMvendedor();
        gestionarVendedor.setVisible(true);
    }//GEN-LAST:event_jMGestionarVendedoresActionPerformed

    private void jMGestionarVendedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMGestionarVendedoresMouseClicked
       
    }//GEN-LAST:event_jMGestionarVendedoresMouseClicked

    private void jMAreasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAreasActionPerformed
        
    }//GEN-LAST:event_jMAreasActionPerformed

    private void jMVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMVendedoresActionPerformed
        // TODO add your handling code here:
        ComisionV unaComisionV = new ComisionV();
        unaComisionV.setVisible(true);
    }//GEN-LAST:event_jMVendedoresActionPerformed

    private void jMAreasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMAreasMouseClicked
        VentanaArea unArea = new VentanaArea();
        unArea.setVisible(true);
    }//GEN-LAST:event_jMAreasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMAreas;
    private javax.swing.JMenu jMCobranzas;
    private javax.swing.JMenuItem jMComisionV;
    private javax.swing.JMenuItem jMGestionarVendedores;
    private javax.swing.JMenuItem jMIngresos;
    private javax.swing.JMenuItem jMListado;
    private javax.swing.JMenuItem jMReporte;
    private javax.swing.JMenu jMVendedores;
    private javax.swing.JMenuBar jMenuBar;
    // End of variables declaration//GEN-END:variables
}
